<a href="https://colab.research.google.com/github/sree44825-sudo/numpy/blob/main/numpy_luminar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  # numerical python

#array : collection of data with same datatype (Homogenious)

a=np.array([1,2,3,4])
a
a=np.array([1,2,3.0,4])
a
a=np.array([1,2,3.0,4,"a"])
print(a)


['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing
#slicing forward, backward slicing

import numpy as np

a=np.array([1,2,3,4,5])
print(a[2:3])
#1,2
a=np.array([1,2,3,4,5])
print(a[0:2])
#5,4
a=np.array([1,2,3,4,5])
print(a[-1:-3:-1])
#4,5
a=np.array([1,2,3,4,5])
print(a[3::])
#2,1
a=np.array([1,2,3,4,5])
print(a[-4::-1])


[3]
[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension

a=np.array([0,1,2,3,4,5])
b=np.array([[1,2],[3,4]])

print(a.ndim)  #dimension =1 vector
print(b.ndim)  #dimension =2 matrix

print(b)

print(b.shape)  #To know how many rows and columns

1
2
[[1 2]
 [3 4]]
(2, 2)


In [ ]:
#create a 2*2 matrix 2,3 4,5

import numpy as np

a=np.array([[2,3],[4,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[2 3]
 [4 5]]
2
(2, 2)
4


In [ ]:
#create a 2*3 matrix and print ,size, shape, dimension

import numpy as np

a=np.array([[1,2,3],[4,5,6]])

print(a)
print(a.ndim)  #To find how many dimension
print(a.shape) #To find how many columns and rows
print(a.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [ ]:
#create a 4*2 matrix display its size , shape , dimension

import numpy as np

a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [ ]:
#create a  4*4 matrix

import numpy as np

z=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])
print(z)
print(z.ndim)
print(z.shape)
print(z.size)
print(z[0])  #To access the specific row
print(z[:,0]) #To accesss specific column
print(z[1,3])
print(z[3,2:])
print(z[2:,2:])
print(z[3,1:3])
print(z[1:4,3])
print(z[:0,1])

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]
2
(4, 4)
16
[1 2 3 4]
[1 5 9 5]
8
[3 2]
[[7 6]
 [3 2]]
[4 3]
[8 6 2]
[]


In [ ]:
#zero matrix

z=np.zeros([3,3])

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z=np.zeros([3,3],dtype=complex)
print(z)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [ ]:
#one matrix

z=np.ones([3,3])
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.ones([3,3],dtype=complex)
print(z)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [ ]:
#create two 2*2 matrix

import numpy as np
a=np.array([[1,2],[2,3]])
b=np.array([[4,5],[6,7]])
print(a)
print(b)

[[1 2]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
#matrix addition

print(a+b)

[[ 5  7]
 [ 8 10]]


In [ ]:
#matrix substraction

print(a-b)

[[-3 -3]
 [-4 -4]]


In [ ]:
#matrix multiplication

print(a*b)  #Not a matrix multiplication
print()
print(a@b)  #Correct matrix multiplication
print()
print(a.dot(b)) #matrix multiplication
print()
print(a/b) # matrix division     #Those starting with __ are called magic

[[ 4 10]
 [12 21]]

[[16 19]
 [26 31]]

[[16 19]
 [26 31]]

[[0.25       0.4       ]
 [0.33333333 0.42857143]]


In [ ]:
#full matrix

z=np.full([3,3],4,dtype=int)  #if all the elements  in the matrix is same its called  full matrix

print(z)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
#create 3x4 matrix with value 9 and datatype complex

import numpy as np
a=np.full([3,4],9,dtype=complex)
print(a)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix

a=np.identity(3)
print(a)
print()
z=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a 4x4 matrix

a=np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6],[5,4,3,2]])
print(a)
print()
print(a.size)
print()


[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]

16



In [ ]:
b=a.reshape(8,2)  #reshape can change the shape of the matrix
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 8]
 [7 6]
 [5 4]
 [3 2]]


In [ ]:
#arange    arrange a particular range of numbers

a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
#create a 3x3 matrix with float values

a=np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
print(a)


[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]


In [ ]:
#floor

z=np.floor(a)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
#ceil

y=np.ceil(a)
print(y)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
#round

y=np.round(a)
print(y)

#incase of .5 it round towards even number eg 3.5 -> 4

[[ 1.  2.  3.]
 [ 4.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
#create a 3x3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)
print()
print(a.max())  #To find the maximum value
print()
print(a.max(axis=1))  #To find the max element in every row(1)
print()
print(a.max(axis=0))  #To find the max element in every column(0)
print()
print(a.min())
print()
print(a.min(axis=1))  #To find the min element in every row(1)
print()
print(a.min(axis=0))  #To find the min element in every column(0)
print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))
print()
print(np.sqrt(a))
print()
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))
print()



[[1 2 3]
 [4 5 6]
 [7 8 9]]

9

[3 6 9]

[7 8 9]

1

[1 4 7]

[1 2 3]

[12 15 18]

[ 6 15 24]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]



In [ ]:
print(a.sum(axis=0))
print()
print(a.sum(axis=1))
print()
print(np.sqrt(a))
print()
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))
print()
print(a.flatten())
print()

[12 15 18]

[ 6 15 24]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]

[1 2 3 4 5 6 7 8 9]



In [ ]:
print(a.flatten())

[1 2 3 4 5 6 7 8 9]


In [ ]:
#sort
#create a 3x3 matrix

import numpy as np
a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
print()

b=np.sort(a,axis=0)
print(b)
print()

c=np.sort(a,axis=1)
print(c)
print()

d=np.argsort(a,axis=1) #index based workinf function
print(d)



[[3 4 1]
 [5 3 1]
 [6 9 8]]

[[3 3 1]
 [5 4 1]
 [6 9 8]]

[[1 3 4]
 [1 3 5]
 [6 8 9]]

[[2 0 1]
 [2 1 0]
 [0 2 1]]
